### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by dostoievsky** [DQ0408/MBGE-recognition#3]
the dataset its the date used to train the algorithm?

I can use homemade samples to do so?

and what if I only want to insert data and see how the algorithm predicts it?

Can you help me? Thank you!

**Comment by DQ0408** [comment]
[1] The dataset used to train the algorithm is described in [here](https://ieeexplore.ieee.org/abstract/document/8803460), which could be downloaded via contacting my former colleague with email: zj.shen@siat.ac.cn
[2&3] Absolutely sure, you shoul keep the data path with the same form of our project, which could be inferred from our codes with some efforts.
[4] Hope that the information is helpful to you.

**Comment by dostoievsky** [comment]
@DQ0408 Hello, you surely help me, and I found your work as realy good and impressive!

lets suposse I put the data at  ~/develop/MBGE-recognition/dataset 

what kind of data it should be? RGB video?  In any format? .webdm, .mp4, etc?

then, there is the command:

nvidia-docker run -it -v **absolute path to dataset**:/data bitxiong/tsn:latest bash

that could become:

```
nvidia-docker run -it -v ~/develop/MBGE-recognition/dataset :/data bitxiong/tsn:latest bash

```

What that command are doing, when I tried that comand, it did not worked, and I have downloaded the nvidia-docker correctly,
but, the command 


```
docker run --gpus all -it -v ~/develop/MBGE-recognition/dataset :/data bitxiong/tsn:latest bash

```

worked, its the same thing? Or it dosen't.

I didn't get what the command did, he's like, copying the content of dataset folder inside the image of bitxiong?

If that so, even without any dataset, the contents that already into this repo didnt got inside the docker volume!

```
        cp /data/build_of.py ./tools/
        python ./tools/build_of.py /data/video/ /data/optical_flow_data/
        exit
```
the content '/data/build_of.py" witch is 'dataset/build_of.py' did not worked, because there is no such content on '/data',
the only things inside that container folder on my pc are:

"activitynet_splits  hmdb51_splits  tsn_tiny.png  ucf101_splits"

I am a computer science student on brasil, doing the Image process class. 

At that class, I need to do a experiment about emotion recognition on surveillance cameras.

So I'm really focused on body recognition based system than facials one, 
due that surveillance cameras in a common basis, are low quality and do not get faces in a good position most of times.

So i've found that dataset:
https://viratdata.org/

witch are a video collection of surveillance cameras ambient, and I want to try run that algorithm to see if emotions get
recognized.  Well I think more of one people will be on that video, if so, each one of them should be coped to worked 
with your algorithm, or it can detect multiple subjects?

Finally, i found a really nice experiment on github about facial/body emotion recognition that can interest you as well:
https://github.com/filby89/body-face-emotion-recognition

In that experiment, there's a pre-processing that converts the video flow into keypoints with openpose and openface,
and I don't know with that algorithm can recognize multiple subjects as well. 

Thank you for exchanging information with me!

I'm really pleased, greetings from brasil, 

Bernardo.

**Comment by DQ0408** [comment]
Hi @dostoievsky , 
[1] Since a long time has passed, I can't remember the specific data format and path at that time. But Most Probably MP4.
[2] It seems that the docker versions are different between us. The command that woked on your machine could be used.
[3] It seems that '/data/build_of.py' has been moved if didn't exist in tsn docker. Any script which can generate optical flow data can be used here.
[4] Unfortunately, our code does not work for multiple people.
Hope you enjoying your Image process class and sorry for not being able to provide more specific help.
Eric.

**Comment by dostoievsky** [comment]
I really thank you! I'll try do some experiments with your code, and I share the results with you, if that pleases you! 
I'll close this issue since I think all the question I had are answered and that will help me work with your code.

**Comment by shenyujie1125** [comment]
I am a graduate student at Xidian University and am very interested in your research, I have contacted your former colleagues to obtain datasets for scientific research, but have not yet received a response.

**Comment by shenyujie1125** [comment]
> I am a graduate student at Xidian University and am very interested in your research, I have contacted your former colleagues to obtain datasets for scientific research, but have not yet received a response.

Can you help me? Thank you!

**Comment by shenyujie1125** [comment]
Can you help me? Thank you!

**Comment by DQ0408** [comment]
@shenyujie1125 You can contact Zhijuan Shen with email: [zj.shen@siat.ac.cn](mailto:zj.shen@siat.ac.cn). I don't have a copy of this dataset cause the restriction of data protocols.

**Comment by shenyujie1125** [comment]
> @shenyujie1125 You can contact Zhijuan Shen with email: [zj.shen@siat.ac.cn](mailto:zj.shen@siat.ac.cn). I don't have a copy of this dataset cause the restriction of data protocols.

Thanks for your response, I will continue trying to contacn through emait your former colleague Zhijuan Shen through email. I was very interested in your previous work in emotion recognition based on body movements.  I hope she will give me a reply, and I hope my research can continue,  to build an emotion recognition algorithm that is independent of body movements, rather than building an emotion recognition system for some specific body movements.

**Comment by shenyujie1125** [comment]
> 



> @shenyujie1125 You can contact Zhijuan Shen with email: [zj.shen@siat.ac.cn](mailto:zj.shen@siat.ac.cn). I don't have a copy of this dataset cause the restriction of data protocols.

Thanks for your response, I will continue trying to contact your former colleague Zhijuan Shen through email. I was very interested in your previous work in emotion recognition based on body movements. I hope she will give me a reply, and I hope my research can continue, to build an emotion recognition algorithm that is independent of body movements, rather than building an emotion recognition system for some specific body movements.
